/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1b1b',
        'on-primary-container': '#a8e7c5',
        'on-error': '#ffffff',
        'on-secondary-container': '#6f5c00',
        'on-secondary-fixed-variant': '#554600',
        secondary: '#705d00',
        'outline-variant': '#bfc9c1',
        'on-secondary': '#ffffff',
        'inverse-surface': '#313030',
        tertiary: '#42493f',
        'on-primary': '#ffffff',
        'primary-container': '#2d6a4f',
        'tertiary-container': '#5a6156',
        outline: '#707973',
        'secondary-container': '#fdd404',
        'tertiary-fixed': '#dee5d6',
        'tertiary-fixed-dim': '#c2c9bb',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#0e5138',
        'primary-fixed-dim': '#95d4b3',
        background: '#fcf9f8',
        error: '#ba1a1a',
        surface: '#fcf9f8',
        'on-surface-variant': '#404943',
        'surface-tint': '#2c694e',
        'surface-dim': '#dcd9d9',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#42493e',
        'inverse-primary': '#95d4b3',
        'on-tertiary-fixed': '#171d14',
        'secondary-fixed': '#ffe171',
        'surface-container-high': '#eae7e7',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        'surface-bright': '#fcf9f8',
        'on-secondary-fixed': '#221b00',
        'on-background': '#1b1b1b',
        'surface-container-highest': '#e5e2e1',
        'on-primary-fixed': '#002114',
        'surface-variant': '#e5e2e1',
        'primary-fixed': '#b1f0ce',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#d5dccd',
        primary: '#0f5238',
        'surface-container': '#f0eded',
        'surface-container-low': '#f6f3f2',
        'secondary-fixed-dim': '#e9c400',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
        'body-lg': ['Work Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'label-bold': ['Work Sans'],
        'body-md': ['Work Sans'],
        'label-sm': ['Work Sans'],
      },
      spacing: {
        'container-max': '1280px',
        'margin-desktop': '64px',
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '20px',
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.15' }],
        'display-lg-mobile': ['2.5rem', { lineHeight: '1.15' }],
        'headline-md': ['2rem', { lineHeight: '1.25' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.3' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'body-md': ['0.95rem', { lineHeight: '1.6' }],
        'label-bold': ['0.85rem', { lineHeight: '1.2' }],
        'label-sm': ['0.7rem', { lineHeight: '1.2' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
